const animals = [
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Totoaba.jpg",
    id: "1",
    name: "Totoaba",
    scientificName: "Totoaba macdonaldi",
    type: "Fish",
    zone: "Gulf of Mexico",
    status: "Extinction danger",
  },
  {
    id: "2",
    name: "Tortuga Carey",
    scientificName: "Eretmochelys imbricata",
    type: "Reptile",
    zone: "Gulf of Mexico",
    status: "Extinction danger",
  },

  {
    id: "3",
    name: "Vaquita marina",
    scientificName: "Phocoena sinus",
    type: "Mammal",
    zone: "Gulf of Mexico",
    status: "Extinction danger",
  },
  {
    id: "4",
    name: "Ballena azul",
    scientificName: "Balaenoptera musculus",
    type: "Mammal",
    zone: "all the oceans",
    status: "Extinction danger",
  },
  {
    id: "5",
    name: "tortuga Lora",
    scientificName: "Lepidochelys kempii",
    type: "Reptile",
    zone: "Gulf of Mexico",
    status: "Extinction danger",
  },
  {
    id: "6",
    name: "León marino de Steller",
    scientificName: "Eumetopias jubatus",
    type: "Mammal",
    zone: "North pacific",
    status: "Extinction danger",
  },
  {
    id: "7",
    name: "Tiburón martillo gigante",
    scientificName: "Sphyrna mokarran",
    type: "Fish",
    zone: "Gulf of Mexico",
    status: "Extinction danger",
  },
  {
    id: "8",
    name: "Rorcual común",
    scientificName: "Balaenoptera physalus",
    type: "Mammal",
    zone: "Gulf of Mexico",
    status: "Vulnerable",
  },
  {
    id: "9",
    name: "Delfín de cabeza blanca",
    scientificName: "Cephalorhynchus hectori",
    type: "Mammal",
    zone: "New Zealand",
    status: "Extinction danger",
  },
  {
    id: "10",
    name: "Tortuga verde",
    scientificName: "Chelonia mydas",
    type: "Reptile",
    zone: "Atlantic & Pacific",
    status: "Extinction danger",
  },
  {
    id: "11",
    name: "Manatí",
    scientificName: "Trichechus manatus",
    type: "Mammal",
    zone: "Carribean",
    status: "Extinction danger",
  },
  {
    id: "12",
    name: "Foca Monje Mediterránea",
    scientificName: "Monachus monachus",
    type: "Mammal",
    zone: "Italy",
    status: "Extinction danger",
  },
  {
    id: "13",
    name: "Ballena gris",
    scientificName: "Eschrichtius robustus",
    type: "Mammal",
    zone: "Pacific",
    status: "Extinction danger",
  },
  {
    id: "14",
    name: "Tiburon blanco",
    scientificName: "Carcharodon carcharias",
    type: "Fish",
    zone: "Pacific & Antlantic",
    status: "Extinction danger",
  },
  {
    id: "15",
    name: "Pez Napoleón",
    scientificName: "Cheilinus undulatus",
    type: "Fish",
    zone: "Pacific",
    status: "Extinction danger",
  },
  {
    id: "16",
    name: "Delfín del río Irrawaddy",
    scientificName: "Orcaella brevirostris",
    type: "Mammal",
    zone: "Asia",
    status: "Extinction danger",
  },
  {
    id: "17",
    name: "Tiburón raya",
    scientificName: "Rhina ancylostoma",
    type: "Fish",
    zone: "Australia , japan",
    status: "Extinction danger",
  },
  {
    id: "18",
    name: "Nutria marina",
    scientificName: "Enhydra lutris",
    type: "Mammal",
    zone: "North pacific",
    status: "Extinction danger",
  },
  {
    id: "19",
    name: "Tiburon ballena",
    scientificName: "Rhincodon Typus",
    type: "Fish",
    zone: "Yucatan & Philipines",
    status: "Extinction danger",
  },
  {
    id: "20",
    name: "Raya águila de cabeza larga",
    scientificName: "Aetobatus flagellum",
    type: "Fish",
    zone: "India, Indonesia",
    status: "Extinction danger",
  },
  {
    id: "21",
    name: "Pez de sierras estrechas",
    scientificName: "Anoxypristis cuspidata",
    type: "Fish",
    zone: "Australia",
    status: "Extinction danger",
  },
  {
    id: "22",
    name: "Sargo cabezón",
    scientificName: "Chrysoblephus gibbiceps",
    type: "Fish",
    zone: "South Africa",
    status: "Extinction danger",
  },
  {
    id: "23",
    name: "Pez luna",
    scientificName: "Mola mola",
    type: "Fish",
    zone: "South Africa",
    status: "Extinction danger",
  },
  {
    id: "24",
    name: "Cornuda planeadora",
    scientificName: "Eusphyra blochii",
    type: "Fish",
    zone: "Australia",
    status: "Extinction danger",
  },
  {
    id: "25",
    name: "Tiburón mudo",
    scientificName: "Centrophorus harrissoni",
    type: "Fish",
    zone: "Australia",
    status: "Extinction danger",
  },
];
module.exports = animals;
